server:
  port: 9001

spring:
  application:
    name: authentication-service
  resources:
    chain:
      enabled: true
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${random.value}
        healthCheckPath: /health-check
        healthCheckInterval: 30s
  datasource:
    url: jdbc:mariadb://localhost:3306/Authentication
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

security:
    oath2:
      resource:
          filter-order: 3
    signing-key: laADFsAFdASFG86AfFHGuSHkGhJasKYnlfGADFHA54213HSD
    encoding-strength: 512
    security-realm: Spring Boot Testing
    jwt:
        client-id: testjwtclientid
        client-secret: al51sdADFfASDuh13
        grant-type: password
        scope-read: read
        scope-write: write
        resource-ids: testjwtresourceid