server:
  port: 9001

spring:
  application:
    name: authentication-service
  resources:
    chain:
      enabled: true
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${random.value}
        healthCheckPath: /health-check
        healthCheckInterval: 30s
  datasource:
    url: jdbc:mariadb://localhost:3306/Authentication
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver


management:
  security:
    enabled: true
