server:
  port: 9002

spring:
  application:
    name: accounts-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${random.value}
        healthCheckPath: /health-check
        healthCheckInterval: 30s

